
  language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
    secure: 73e4df86-6a6c-4052-a54b-ca0a75a18817
  app: devopslabs-helloworld90
  
  